flags:
  time-locale-compat:
    old-locale: false
extra-package-dbs: []
packages:
- '.'
extra-deps:
- QuickCheck-2.11.3
- aeson-1.2.4.0
- attoparsec-0.13.1.0
- base-compat-0.9.3
- dlist-0.8.0.2
- hashable-1.2.4.0
- mtl-2.2.1
- pandoc-types-1.17.0.5
- primitive-0.6.1.0
- random-1.1
- regex-base-0.93.2
- regex-posix-0.95.2
- scientific-0.3.4.9
- syb-0.6
- tagged-0.8.5
- text-1.2.2.1
- tf-random-0.5
- th-abstraction-0.2.6.0
- time-locale-compat-0.1.1.4
- transformers-compat-0.5.1.4
- unordered-containers-0.2.7.1
- uuid-types-1.0.3
- vector-0.11.0.0
resolver: ghc-8.0
