# As of May 2020, this action is supposed to make sure that the project is in a
# compilable state.
on: [push]
name: build
jobs:
  runhaskell:
    name: pandoc-filters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.8'
          cabal-version: '3.0.0.0'
          stack-version: '2.5.1'

      - name: Setup
        run: stack setup

      - name: Build
        run: stack build

      - name: Install
        run: stack install
